constant item_length(32)
constant item_column($20)
constant weapon_column($58)
constant item_counter_column($D0)

origin $003F3000
item_names:
    gameItem("                                ")
    gameItem("ADAGA SIMPLES                   ")
    gameItem("ESPADA                          ")
    gameItem("SABRE                           ")
    gameItem("ESPADA DA MORTE                 ")
    gameItem("ESPADA OMEGA                    ")
    gameItem("ARCO                            ")
    gameItem("ARCO DE FOGO                    ")
    gameItem("ARCO DE METAL                   ")
    gameItem("BOMBA SIMPLES                   ")
    gameItem("BOMBA MÉDIA                     ")
    gameItem("BOMBA GRANDE                    ")
    gameItem("ARCO ATÔMICO                    ")
    gameItem("         CHAVE VERMELHA         ")
    gameItem("           CHAVE AZUL           ")
    gameItem("           CHAVE VERDE          ")
    gameItem("        CHAVE DE MADEIRA        ")
    gameItem("    AUMENTA O SEU NÍVEL EM +1   ")
    gameItem("WATER ST                        ")
    gameItem("FIRE ST.                        ")
    gameItem("SHADOW S                        ")
    gameItem("WOOD ST.                        ")
    gameItem("        RECUPERA A SAÚDE        ")
    gameItem("            IMPULSO             ")
    gameItem("        RECUPERA A MAGIA        ")
    gameItem("            ESPECIAL            ")
    gameItem("    INVOCAR O ESPÍRITO DITTO    ")
    gameItem("    INVOCAR O ESPÍRITO EFREET   ")
    gameItem("    INVOCAR O ESPÍRITO SHADE    ")
    gameItem("     INVOCAR O ESPÍRITO BOW     ")
    gameItem("    RECUPERA A SAÚDE EM +1/4    ")
    gameItem("    RECUPERA A SAÚDE EM +1/2    ")
    gameItem("    RECUPERA A SAÚDE EM +3/4    ")
    gameItem("   RECUPERA A SAÚDE AO MÁXIMO   ")
    gameItem("    RECUPERA A MAGIA EM +1/4    ")
    gameItem("    RECUPERA A MAGIA EM +1/2    ")
    gameItem("    RECUPERA A MAGIA EM +3/4    ")
    gameItem("   RECUPERA A MAGIA AO MÁXIMO   ")
    gameItem(" RECUPERA A SAÚDE/MAGIA EM +1/4 ")
    gameItem(" RECUPERA A SAÚDE/MAGIA EM +1/2 ")
    gameItem(" RECUPERA A SAÚDE/MAGIA EM +3/4 ")
    gameItem("RECUPERA A SAÚDE/MAGIA AO MÁXIMO")
    gameItem("RECUPERA A SAÚDE/MAGIA AO MORRER")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("   UM ESTRANHO E GRANDE CUBO    ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    gameItem("                                ")
    db ENDSTRING