constant item_length(8)
constant item_column($80)
constant weapon_column($70)
constant item_counter_column($B8)

origin $0005CC16
item_names:
    gameItem("        ")
    gameItem("ALTKNIFE")
    gameItem("SWORD   ")
    gameItem("BROAD   ")
    gameItem("DEATH   ")
    gameItem("OMEGA   ")
    gameItem("BOW     ")
    gameItem("FIRE    ")
    gameItem("METAL   ")
    gameItem("BOMB    ")
    gameItem("POWER   ")
    gameItem("HYPER   ")
    gameItem("ATM BOW ")
    gameItem("RED KEY ")
    gameItem("BLUE KEY")
    gameItem("GREE.KEY")
    gameItem("WOOD KEY")
    gameItem("HP UP   ")
    gameItem("WATER ST")
    gameItem("FIRE ST.")
    gameItem("SHADOW S")
    gameItem("WOOD ST.")
    gameItem("HP HEAL ")
    gameItem("BOOSTER ")
    gameItem("SP HEAL ")
    gameItem("SPECIAL ")
    gameItem("DYT CALL")
    gameItem("EFR CALL")
    gameItem("SHD CALL")
    gameItem("BOW CALL")
    gameItem("HP +1/4 ")
    gameItem("HP +1/2 ")
    gameItem("HP +3/4 ")
    gameItem("HP +MAX ")
    gameItem("SP +1/4 ")
    gameItem("SP +1/2 ")
    gameItem("SP +3/4 ")
    gameItem("SP +MAX ")
    gameItem("HPSP+1/4")
    gameItem("HPSP+1/2")
    gameItem("HPSP+3/4")
    gameItem("HPSP+MAX")
    gameItem("ELIXIR  ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("L. CUBE ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    gameItem("        ")
    db ENDSTRING